name: rock_leaf_scissor
description: "Rock Leaf Scissor Game"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  flutter_localizations: 
    sdk: flutter
  intl: any
  provider: ^6.1.5+1
  google_fonts: ^6.3.1
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons: # flutter clean; flutter pub get; flutter pub run flutter_launcher_icons:main
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#00008E"
    theme_color: "#00008E"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
  generate: true
  uses-material-design: true
 
  assets:
    - assets/
    - assets/images/